name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login docker registry
      run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - name: Build docker image
      run: docker build . --file Dockerfile --tag schedule_bot
    - name: Send to registry
      run:  docker push schedule_bot
